[env:pico]

platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow            ; Pico 2 W? change to: rpipico2w
framework = arduino
board_build.core = earlephilhower

upload_protocol = mbed
upload_port = D:\

lib_deps = adafruit/Adafruit Protomatter@^1.7.1
